pipeline {
    agent any
//credentials are passed as environmental variables    
    environment {
        access_key = credentials('access_key')
        secret_key = credentials('secret_key')
        
    }
 // specifies which tools terraform should use to run the job   
    tools{
        terraform 'terraform'
    }
//checksout the code from the github repository
    stages {
        stage('git checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Merch7x/DevOps-Projects.git']])
                        dir('Project 1/') {
                            
                        }
            }
        }
        
//initialises the terraform backend
        stage('initialization') {
            steps {
                 dir('Project 1/') {
                     sh 'pwd'
                     sh 'terraform init'
                 }
            }
        }

// validates the configuration file is correct        
        stage('validation') {
            steps {
                dir('Project 1/') {
                    sh 'terraform validate'
                }
            }
        }

// plans what the config infra will look like       
        stage('plan') {
            steps {
                dir('Project 1/') {
                    sh 'terraform plan -var="access=$access_key" -var="secret=$secret_key"'
                }
            }
        }

// applies the configuration file        
        stage('apply') {
            steps {
                dir('Project 1/') {
                    sh 'terraform apply --auto-approve -var="access=$access_key" -var="secret=$secret_key"'
                }
            }
        }

//destroys the created infrastructure created above
//         stage('destroy') {
//             steps {
//                 dir('Project 1/') {
//                     sh 'terraform destroy --auto-approve -var="access=$access_key" -var="secret=$secret_key"'
//                 }
//             }
//         }
//     }
// }
